{% set name = "Omicron" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.ligo.org/virgo/virgoapp/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 02a3085079f16b47ca1b8473d5cb352575a14d957ef950b9534ec387072ceadb
  patches:
    # use rootcling from build env when cross-compiling
    - rootcling-cross.patch  # [build_platform != target_platform]

build:
  error_overdepending: true
  error_overlinking: true
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.9.0
    - make  # [unix]
    - pkg-config  # [unix]
    - root_base  # [build_platform != target_platform]
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - fftw
    - gwollum {{ version }}
    - root_base
    # https://github.com/conda-forge/root-feedstock/issues/158
    - nlohmann_json >=3.10.5
  run:
    - fftw
    - gwollum
    - root_base

test:
  requires:
    - pkg-config
  commands:
    # sanity check
    - omicron version
    # run test commands
    - for omitest in ${PREFIX}/sbin/omicron-test-*; do ${omitest}; done  # [not osx]
    # check pkg-config
    - pkg-config --print-errors --exact-version {{ version }} {{ name|lower }}
    # check activate variables
    - test "${OMICRON_HTML}" == "${PREFIX}/share/omicron/html"  # [unix]

about:
  home: https://virgo.docs.ligo.org/virgoapp/{{ name }}/
  doc_url: https://virgo.docs.ligo.org/virgoapp/{{ name }}/
  dev_url: https://git.ligo.org/virgo/virgoapp/{{ name }}.git
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: An algorithm to detect and characterize transient events in gravitational-wave detectors
  description: |
    Omicron has been derived from a well-known 'burst-type' search pipeline
    called Q-pipeline (a.k.a Omega).  Q-pipeline is able to detect and
    characterize detector glitches with a very good efficiency and precision.
    So, the idea was to adapt it for detector characterization purposes,
    i.e. to run it over many auxiliary channels.  To achieve this, the
    original matlab code has been replaced by a C++ architecture and many
    steps have been removed to run faster.  The name Omicron was chosen to
    recall the Omega inheritance.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - rhyspoulton
