{% set name = "Omicron" %}
{% set version = "4.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.ligo.org/virgo/virgoapp/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 526ce0737982c77e46dc89127c03d181e66b9e9c3664987c984e1466578766a8
  patches:
    # use rootcling from build env when cross-compiling
    - rootcling-cross.patch  # [osx and arm64]

build:
  error_overdepending: true
  error_overlinking: true
  number: 5
  skip: true  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake >=3.9.0
    - make  # [unix]
    - pkg-config  # [unix]
    - root_base  # [osx and arm64]
  host:
    - fftw
    - gwollum {{ version }}
    - root_base
  run:
    - fftw
    - gwollum
    - root_base

test:
  requires:
    - pkg-config
  commands:
    # sanity check
    - omicron version
    # check pkg-config
    - pkg-config --print-errors --exact-version {{ version }} {{ name|lower }}
    # check activate variables
    - test "${OMICRON_HTML}" == "${PREFIX}/share/omicron/html"  # [unix]

about:
  home: https://virgo.docs.ligo.org/virgoapp/{{ name }}/
  doc_url: https://virgo.docs.ligo.org/virgoapp/{{ name }}/
  dev_url: https://git.ligo.org/virgo/virgoapp/{{ name }}.git
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: An algorithm to detect and characterize transient events in gravitational-wave detectors
  description: |
    Omicron has been derived from a well-known 'burst-type' search pipeline
    called Q-pipeline (a.k.a Omega).  Q-pipeline is able to detect and
    characterize detector glitches with a very good efficiency and precision.
    So, the idea was to adapt it for detector characterization purposes,
    i.e. to run it over many auxiliary channels.  To achieve this, the
    original matlab code has been replaced by a C++ architecture and many
    steps have been removed to run faster.  The name Omicron was chosen to
    recall the Omega inheritance.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - FlorentRobinet
